source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'

target 'IFLYADLibSimple' do
  use_frameworks!

  # 优酷 Model B 单包：只含开屏、插屏和媒体自渲染，模块及公开 API 仍为 IFLYADLib / IFLY*。
  pod 'YKIFLYADLib',
      :podspec => 'https://raw.githubusercontent.com/LJMcarryu/YKIFLYADLib_iOS/6.0.14/YKIFLYADLib.podspec'
end
